server:
  port: 8501
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/Omlink?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=false
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.qq.com
    port: 465
    username: omlink@foxmail.com
    password: yzxlvgncghsjbdig
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    debug: true
    protocol: smtp

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

omlink:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /doc.html/**
      - /webjars/**
      - /v3/**



#  minio:
#    endpointUrl: http://127.0.0.1:9001
#    accessKey: admin
#    secretKey: admin123
#    bucketName: spzx-bucket

